[project]
name = "yolo11_streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "kaggle>=1.7.4.2",
    "opencv-python>=4.11.0.86",
    "pillow>=11.1.0",
    "streamlit>=1.44.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "ultralytics>=8.3.99",
]
